#!/usr/bin/env node


var pgp = require('pg-promise')();
//var edca_db = pgp('postgres://tester:test@fractal3.fractal-ware.com/edca');
var edca_db = pgp('postgres://tester:test@localhost/edca');

var jsonfile = require('jsonfile');

var ocds = require('../../io/ocds');

var inicio = 1
var max = 300;

for (var localid = inicio ; localid <= max ;localid++){

    edca_db.one("select $1 as id, count(1) as count from contractingprocess where id = $1", [localid]).then(function (data) {
        if ( data.count > 0){

            ocds.getOCDSJSON( data.id, "release-package", edca_db).then(function (data) {

                var ocid = data.releases[0].ocid.replace(/\//g,"_").trim();

                console.log(' OCID -> '+ ocid);
                var file = "output/"+ ocid  +/*"_"+data.localid+*/".json";

                delete data.localid;

                jsonfile.writeFileSync(file, data, {spaces: 2}, function(err) {
                    console.error("error: ", err);
                });

            }).catch(function (error) {
                console.log("ERROR: ",error);
            });

        }else{
            console.log ( "Registro inexistente: ", data.id );
        }

    }).catch(function (error) {
        console.log(error);
    });
}
