#!/usr/bin/env node

var pgp = require('pg-promise')();
var edca_db = pgp('postgres://tester:test@localhost/edca');
var jsonfile = require('jsonfile');
var ocds = require('../../io/ocds');

edca_db.manyOrNone('select id from contractingprocess order by ocid').then(function(IDs) {

    edca_db.task(function (t) {
        var data = [];
        for (var id of IDs) {
            //console.log(id );
            data.push(ocds.getOCDSJSON(id.id , "release-package", t));
        }

        return this.batch(data);

    }).then(function (data) {
        for (let i = 0; i < data.length; i++) {

            var ocid = data[i].releases[0].ocid.replace(/\//g, "_").trim();

            console.log('Writing JSON: OCID -> ' + ocid);
            var file = "output/" + ocid +
                //"_"+data.localid+
                ".json";

            delete data[i].localid;

            jsonfile.writeFileSync(file, data[i], {spaces: 2}, function (err) {
                console.error("error: ", err);
            });
        }

        console.log('Success!!!');
        pgp.end(); // this is bad ;)

    }).catch(function (error) {
        console.log(error);
    });
});
